In [2]:
# 1. Create a 5×5 matrix with values 1,2,3,…,25
import numpy as np
matrix_5x5 = np.arange(1, 26).reshape(5, 5)
print("#1\n", matrix_5x5)

#1
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [3]:
# 2. Generate a 4×4 identity matrix using NumPy.
identity_4x4 = np.eye(4)
print("#2\n", identity_4x4)



#2
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [4]:
# 3. Create a 1D array of numbers from 100 to 200 with step size 10.
array_100_200 = np.arange(100, 201, 10)
print("#3\n", array_100_200)


#3
 [100 110 120 130 140 150 160 170 180 190 200]


In [5]:
# 4. Generate a random 3×3 matrix and find its determinant.
rand_3x3 = np.random.rand(3,3)
determinant = np.linalg.det(rand_3x3)
print("#4\nMatrix:\n", rand_3x3, "\nDeterminant:", determinant)


#4
Matrix:
 [[0.55878286 0.52166927 0.85292213]
 [0.1531411  0.17063586 0.40670875]
 [0.40731009 0.11923588 0.05429477]] 
Determinant: 0.016454281418254384


In [6]:
# 5. Create a NumPy array of 10 random integers between 1 and 100.
rand_ints_10 = np.random.randint(1, 101, size=10)
print("#5\n", rand_ints_10)


#5
 [84 61 23 66 58 65  9 39 31 75]


In [7]:
# 6. Reshape a 1D array of size 12 into a 3×4 matrix.
arr_1d_12 = np.arange(12)
reshaped_3x4 = arr_1d_12.reshape(3, 4)
print("#6\n", reshaped_3x4)


#6
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [8]:
# 7. Create two 3×3 matrices and perform matrix multiplication.
mat_a = np.random.randint(1, 10, (3, 3))
mat_b = np.random.randint(1, 10, (3, 3))
mat_mult = np.dot(mat_a, mat_b)
print("#7\nMatrix A:\n", mat_a, "\nMatrix B:\n", mat_b, "\nMultiplication:\n", mat_mult)

#7
Matrix A:
 [[6 6 8]
 [1 5 9]
 [3 8 7]] 
Matrix B:
 [[7 9 4]
 [4 2 2]
 [3 1 4]] 
Multiplication:
 [[90 74 68]
 [54 28 50]
 [74 50 56]]


In [9]:
# 8. Find eigenvalues and eigenvectors of a given 2×2 matrix.
matrix_2x2 = np.array([[4, 2], [1, 3]])
eigvals, eigvecs = np.linalg.eig(matrix_2x2)
print("#8\nEigenvalues:", eigvals, "\nEigenvectors:\n", eigvecs)

#8
Eigenvalues: [5. 2.] 
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [10]:
# 9. Create a 5×5 matrix with random values and extract its diagonal elements.
rand_5x5 = np.random.rand(5, 5)
diag_elements = np.diag(rand_5x5)
print("#9\nMatrix:\n", rand_5x5, "\nDiagonal:", diag_elements)


#9
Matrix:
 [[0.06527157 0.52767459 0.38132355 0.71927153 0.23825705]
 [0.29153092 0.61425577 0.44748336 0.80188457 0.67139539]
 [0.78268941 0.24890572 0.40838494 0.45678406 0.75136648]
 [0.44382205 0.94342049 0.79255006 0.02443149 0.58188033]
 [0.39635661 0.92303018 0.56619435 0.45597036 0.73352617]] 
Diagonal: [0.06527157 0.61425577 0.40838494 0.02443149 0.73352617]


In [11]:
# 10. Generate a 1D array and normalize it (scale values between 0 and 1).
arr = np.random.randint(1, 100, 10)
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print("#10\nOriginal:", arr, "\nNormalized:", normalized_arr)

#10
Original: [59 14 16 19 43 52 35 34  3 39] 
Normalized: [1.         0.19642857 0.23214286 0.28571429 0.71428571 0.875
 0.57142857 0.55357143 0.         0.64285714]


In [12]:
# 11. Sort a NumPy array by row and column.
unsorted = np.array([[3, 2, 1], [6, 5, 4]])
sorted_rows = np.sort(unsorted, axis=1)
sorted_cols = np.sort(unsorted, axis=0)
print("#11\nOriginal:\n", unsorted, "\nSorted by rows:\n", sorted_rows, "\nSorted by columns:\n", sorted_cols)


#11
Original:
 [[3 2 1]
 [6 5 4]] 
Sorted by rows:
 [[1 2 3]
 [4 5 6]] 
Sorted by columns:
 [[3 2 1]
 [6 5 4]]


In [13]:
# 12. Find the indices of maximum and minimum values in a NumPy array.
arr_12 = np.array([5, 3, 9, 1, 7])
max_index = np.argmax(arr_12)
min_index = np.argmin(arr_12)
print("#12\nArray:", arr_12, "\nMax index:", max_index, "\nMin index:", min_index)


#12
Array: [5 3 9 1 7] 
Max index: 2 
Min index: 3


In [14]:
# 13. Create a 2D array and flatten it using ravel() and flatten().
arr_2d = np.array([[1, 2], [3, 4]])
flatten_ravel = arr_2d.ravel()
flatten_flatten = arr_2d.flatten()
print("#13\nOriginal:\n", arr_2d, "\nravel():", flatten_ravel, "\nflatten():", flatten_flatten)

#13
Original:
 [[1 2]
 [3 4]] 
ravel(): [1 2 3 4] 
flatten(): [1 2 3 4]


In [15]:
# 14. Create a 3×3 matrix and compute its inverse using NumPy.
mat_3x3 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
inverse_mat = np.linalg.inv(mat_3x3)
print("#14\nMatrix:\n", mat_3x3, "\nInverse:\n", inverse_mat)

#14
Matrix:
 [[1 2 3]
 [0 1 4]
 [5 6 0]] 
Inverse:
 [[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [16]:
# 15. Generate a random permutation of numbers 1 to 10.
perm_1_to_10 = np.random.permutation(np.arange(1, 11))
print("#15\n", perm_1_to_10)

#15
 [ 7  2 10  3  9  1  8  4  6  5]


In [17]:
# 16. Create a NumPy array with values from 0 to 20 and replace all even numbers with -1.
arr_0_20 = np.arange(21)
arr_0_20[arr_0_20 % 2 == 0] = -1
print("#16\n", arr_0_20)


#16
 [-1  1 -1  3 -1  5 -1  7 -1  9 -1 11 -1 13 -1 15 -1 17 -1 19 -1]


In [18]:
# 17. Compute the dot product of two arrays.
a17 = np.array([1, 2, 3])
b17 = np.array([4, 5, 6])
dot_product = np.dot(a17, b17)
print("#17\nDot product:", dot_product)


#17
Dot product: 32


In [19]:
# 18. Generate a 5×5 random matrix and compute its trace.
rand_5x5_18 = np.random.rand(5, 5)
trace_val = np.trace(rand_5x5_18)
print("#18\nMatrix:\n", rand_5x5_18, "\nTrace:", trace_val)

#18
Matrix:
 [[0.29104975 0.67642951 0.45593778 0.21645278 0.33693329]
 [0.86058418 0.87905087 0.06984555 0.14332068 0.17487285]
 [0.44683956 0.02103281 0.69715472 0.28254799 0.53553843]
 [0.08216805 0.10762536 0.08571213 0.97736234 0.73198328]
 [0.69505604 0.75430442 0.08550517 0.04867502 0.64816983]] 
Trace: 3.492787506551868


In [20]:
# 19. Split a 1D array into 3 equal parts.
arr_19 = np.arange(9)
split_3 = np.array_split(arr_19, 3)
print("#19\n", split_3)

#19
 [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [21]:
# 20. Create a 3D array of shape (3,3,3) and find its mean across axis=0.
arr_3d = np.random.rand(3, 3, 3)
mean_axis0 = np.mean(arr_3d, axis=0)
print("#20\nMean across axis 0:\n", mean_axis0)

#20
Mean across axis 0:
 [[0.31821032 0.45704357 0.39667165]
 [0.29244982 0.57793879 0.62077455]
 [0.53764838 0.69492677 0.2335048 ]]


In [22]:
# 21. Find the cumulative sum of a NumPy array.
arr_21 = np.array([1, 2, 3, 4])
cumsum_arr = np.cumsum(arr_21)
print("#21\nCumulative sum:", cumsum_arr)


#21
Cumulative sum: [ 1  3  6 10]


In [23]:
# 22. Create a 4×4 matrix with random integers and extract its upper triangular matrix.
rand_4x4 = np.random.randint(1, 10, (4, 4))
upper_tri = np.triu(rand_4x4)
print("#22\nMatrix:\n", rand_4x4, "\nUpper triangular:\n", upper_tri)

#22
Matrix:
 [[6 3 2 7]
 [4 1 4 6]
 [6 3 6 6]
 [9 5 9 6]] 
Upper triangular:
 [[6 3 2 7]
 [0 1 4 6]
 [0 0 6 6]
 [0 0 0 6]]


In [24]:
# 23. Generate a 6×6 checkerboard pattern (0,1).
checkerboard = np.indices((6,6)).sum(axis=0) % 2
print("#23\nCheckerboard:\n", checkerboard)

#23
Checkerboard:
 [[0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]
 [0 1 0 1 0 1]
 [1 0 1 0 1 0]]


In [25]:
# 24. Generate a 3×3 random matrix and apply element-wise square root.
rand_3x3_24 = np.random.rand(3, 3) * 100
sqrt_matrix = np.sqrt(rand_3x3_24)
print("#24\nOriginal:\n", rand_3x3_24, "\nSquare root:\n", sqrt_matrix)

#24
Original:
 [[22.47756739  5.18486331 53.29532989]
 [45.78677446 31.15747402 21.60616442]
 [51.49653398 73.63617834 95.08422393]] 
Square root:
 [[4.7410513  2.27702949 7.30036505]
 [6.76659253 5.58188803 4.64824315]
 [7.17610855 8.58115251 9.75111398]]


In [26]:
# 25. Create a 1D array of 20 elements and reverse it without using Python slicing.
arr_25 = np.arange(20)
reversed_arr = np.flip(arr_25)
print("#25\nOriginal:", arr_25, "\nReversed:", reversed_arr)

#25
Original: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 
Reversed: [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [27]:
# 26. Merge two NumPy arrays vertically and horizontally.
a26 = np.array([[1, 2], [3, 4]])
b26 = np.array([[5, 6], [7, 8]])
vert_merge = np.vstack((a26, b26))
horz_merge = np.hstack((a26, b26))
print("#26\nVertical merge:\n", vert_merge, "\nHorizontal merge:\n", horz_merge)

#26
Vertical merge:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 
Horizontal merge:
 [[1 2 5 6]
 [3 4 7 8]]


In [28]:
# 27. Create a 2D NumPy array and compute row-wise and column-wise sum.
arr_27 = np.array([[1, 2, 3], [4, 5, 6]])
row_sum = np.sum(arr_27, axis=1)
col_sum = np.sum(arr_27, axis=0)
print("#27\nRow-wise sum:", row_sum, "\nColumn-wise sum:", col_sum)

#27
Row-wise sum: [ 6 15] 
Column-wise sum: [5 7 9]


In [29]:
# 28. Replace NaN values in an array with the mean of that column.
arr_28 = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
col_mean = np.nanmean(arr_28, axis=0)
inds = np.where(np.isnan(arr_28))
arr_28[inds] = np.take(col_mean, inds[1])
print("#28\n", arr_28)

#28
 [[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


In [30]:
# 29. Generate two 1D arrays and compute cosine similarity using NumPy.
a29 = np.array([1, 2, 3])
b29 = np.array([4, 5, 6])
cos_sim = np.dot(a29, b29) / (np.linalg.norm(a29) * np.linalg.norm(b29))
print("#29\nCosine similarity:", cos_sim)

#29
Cosine similarity: 0.9746318461970762


In [31]:
# 30. Create a 4×4 array and rotate it by 90 degrees using NumPy.
arr_30 = np.arange(16).reshape(4,4)
rotated_90 = np.rot90(arr_30)
print("#30\nOriginal:\n", arr_30, "\nRotated 90 degrees:\n", rotated_90)

#30
Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
Rotated 90 degrees:
 [[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]


In [32]:
# 31. Create a structured NumPy array with fields (name, age, marks).
dtype = [('name', 'U10'), ('age', 'i4'), ('marks', 'f4')]
values = [('Alice', 25, 88.5), ('Bob', 22, 92.0)]
structured_arr = np.array(values, dtype=dtype)
print("#31\n", structured_arr)


#31
 [('Alice', 25, 88.5) ('Bob', 22, 92. )]


In [33]:
# 32. Generate a random 3×3 matrix and compute its rank.
rand_3x3_32 = np.random.rand(3,3)
rank_32 = np.linalg.matrix_rank(rand_3x3_32)
print("#32\nMatrix:\n", rand_3x3_32, "\nRank:", rank_32)

#32
Matrix:
 [[0.6502888  0.06253419 0.39871001]
 [0.56758835 0.53114806 0.70200924]
 [0.84787857 0.95003399 0.95985743]] 
Rank: 3


In [34]:
# 33. Create a 5×5 random matrix and normalize each row to have unit length.
rand_5x5_33 = np.random.rand(5,5)
norms = np.linalg.norm(rand_5x5_33, axis=1, keepdims=True)
normalized_rows = rand_5x5_33 / norms
print("#33\nNormalized rows:\n", normalized_rows)

#33
Normalized rows:
 [[0.57208982 0.55283183 0.55810379 0.17629662 0.15662014]
 [0.28552542 0.54318795 0.08000123 0.53171207 0.57819043]
 [0.64632138 0.33774756 0.46258888 0.07413583 0.49870901]
 [0.0224998  0.40939346 0.46052294 0.57204533 0.54090066]
 [0.85348257 0.34950864 0.18515523 0.10094929 0.32394136]]


In [35]:

# 34. Check whether two arrays are equal element-wise.
arr_34_a = np.array([1, 2, 3])
arr_34_b = np.array([1, 2, 4])
equal_elements = np.equal(arr_34_a, arr_34_b)
print("#34\nElement-wise equality:", equal_elements)

#34
Element-wise equality: [ True  True False]


In [36]:
# 35. Generate a random dataset of 1000 numbers and compute histogram.
data_35 = np.random.randn(1000)
hist, bin_edges = np.histogram(data_35, bins=10)
print("#35\nHistogram counts:", hist, "\nBin edges:", bin_edges)

#35
Histogram counts: [  5  20  71 178 260 271 126  55  12   2] 
Bin edges: [-3.40471283 -2.70012396 -1.99553509 -1.29094622 -0.58635735  0.11823152
  0.82282039  1.52740926  2.23199813  2.936587    3.64117587]


In [37]:
# 36. Create a 2D array and apply broadcasting to add a 1D array.
arr_36_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_36_1d = np.array([10, 20, 30])
broadcasted_sum = arr_36_2d + arr_36_1d
print("#36\nBroadcasted sum:\n", broadcasted_sum)

#36
Broadcasted sum:
 [[11 22 33]
 [14 25 36]]


In [38]:
# 37. Find unique values and their counts in a NumPy array.
arr_37 = np.array([1, 2, 2, 3, 3, 3])
unique_vals, counts = np.unique(arr_37, return_counts=True)
print("#37\nUnique values:", unique_vals, "\nCounts:", counts)

#37
Unique values: [1 2 3] 
Counts: [1 2 3]


In [39]:

# 38. Create two arrays and find Pearson correlation coefficient using NumPy.
a38 = np.array([1, 2, 3, 4, 5])
b38 = np.array([5, 4, 3, 2, 1])
corr_coeff = np.corrcoef(a38, b38)[0, 1]
print("#38\nPearson correlation coefficient:", corr_coeff)




#38
Pearson correlation coefficient: -0.9999999999999999


In [40]:
# 39. Compute numerical gradient of a 1D array.
arr_39 = np.array([1, 2, 4, 7, 11])
gradient = np.gradient(arr_39)
print("#39\nNumerical gradient:", gradient)

#39
Numerical gradient: [1.  1.5 2.5 3.5 4. ]


In [41]:

# 40. Generate a random 3×3 matrix and perform Singular Value Decomposition (SVD).
rand_3x3_40 = np.random.rand(3,3)
U, S, Vt = np.linalg.svd(rand_3x3_40)
print("#40\nU:\n", U, "\nSingular values:", S, "\nVt:\n", Vt)

#40
U:
 [[-0.57759644  0.45453895 -0.67806835]
 [-0.71123116 -0.68790096  0.14471522]
 [-0.40066517  0.56585034  0.72061142]] 
Singular values: [1.65976078 0.54326842 0.15436614] 
Vt:
 [[-0.40035827 -0.37290612 -0.83705095]
 [ 0.54808761 -0.82949787  0.10739301]
 [ 0.73437949  0.41578157 -0.53648155]]
